### ISSUE TITLE
[lio_sam_mapOptmization-5] process has died

### ISSUE THREAD

**Issue by jjbecomespheh** [TixiaoShan/LIO-SAM#191]
Hi Ti Xiao Shan,

Im sorry to trouble you, but I have followed the step for installation but I encountered mapOptimization crash and Im not sure how to fix it.

[093B3F78-EC9A-4A3D-A375-8BA4AC8ABD49](https://user-images.githubusercontent.com/50895766/104686435-28d89600-5738-11eb-8b2c-583ec1d770a0.jpeg)
![8D59C257-DAA3-4F33-8587-8FBF9EDEDA2D_1_105_c](https://user-images.githubusercontent.com/50895766/104686365-08a8d700-5738-11eb-9819-d37306ef32ad.jpeg)
![E5562AD0-1A78-4309-ADC6-554BABBBEA0B](https://user-images.githubusercontent.com/50895766/104686379-0f374e80-5738-11eb-9785-449168cd2d43.jpeg)

**Comment by jjbecomespheh** [comment]
I have installed 4.0.2 GTSAM according to the Readme, I also tried 4.0.3 GTSAM but it did not work as well.

**Comment by jjbecomespheh** [comment]
Okay, I have solved the problem.

Initially, I upzip and move the gtsam folder into my src folder of my workspace. Which I follow the step
mkdir build && cd build
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
sudo make install -j8
I also compile LIO-SAM afterwards.
and I encounter mapoptimization crashing, which is due to gtsam as mentioned by @TixiaoShan in the Readme.

So I rm gtsam from my workspace, put it inside my root folder instead and run
mkdir build && cd build
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
sudo make install -j8
at there.
The problem was resolved.

**Comment by alwynmathew** [comment]
@jjbecomespheh I installed GTSAM 4.0 with the ppa given in the README and was able to compile the package successfully following https://github.com/TixiaoShan/LIO-SAM/issues/206 in ROS Noetic (Ubuntu 20.04) but I still get `[lio_sam_mapOptmization-4] process has died [pid 174714, exit code -6` when I launch the package. Were you using ROS noetic here?

**Comment by syedjameel** [comment]
It is because of the GTSAM lib, 
I followed the following env configuration and it works fine (for ROS noetic): 
https://cheeson.xyz/2023/10/09/LIO-SAM/

**Comment by sahith-chada** [comment]
I followed the steps @syedjameel  mentioned to install GTSAM lib, but even then I got the same error ([lio_sam_mapOptmization-5] process has died [pid 1146996, exit code -6) when I launched the package and ran the rosbag.
I am using ROS Noetic. Is there any fix?

**Comment by syedjameel** [comment]
@sahith-chada, make sure to uninstall other versions of gtsam libs before following that env configuration.
